[package]
name = "codinterm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.89"
axum = "0.7.6"
crossbeam = "0.8.4"
tokio = {version="1.40.0", features=["macros","rt-multi-thread"]}
